server:
  port: 8080

spring:
  elasticsearch:
    uris: http://localhost:9200

logging:
  config: classpath:config/logback-spring.xml
  level:
    com.spring: debug
#    tracer: TRACE
#    org:
#      elasticsearch:
#        client: TRACE
